#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ./mwc.pl -type make ../cs363-fall2021-assignment4
#
#----------------------------------------------------------------------------


all: ssignment4

depend: ssignment4-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.ssignment4 $(@)

.PHONY: ssignment4
ssignment4:
	@$(MAKE) -f Makefile.ssignment4 all

.PHONY: ssignment4-depend
ssignment4-depend:
	@$(MAKE) -f Makefile.ssignment4 depend

project_name_list:
	@echo ssignment4
